name: 'Copilot reverse engineer'
description: 'Copilot reverse engineer'
branding:
  icon: terminal
  color: 'blue'
author: 'StopWar'
runs:
  using: 'composite'
  steps:
    - run: ${{ github.action_path }}/index.sh
      shell: bash
  post:
    - run: ${{ github.action_path }}/main.sh
      shell: bash
